Contents = function(item) {
	switch(item){
		// Header
		// case "mod_header01":
		// 	var contents = "";
		// 		//contents += "<script src='https://code.jquery.com/jquery-1.12.4.min.js' integrity='sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=' crossorigin='anonymous'></script>\n";
		// 		contents += "<div class='module-wrap edit_wrap com_mod_header sty01'>\n";
		// 		contents += "<div class='cnt-container header clearfix'>\n";
		// 		contents += "<div class='biz_cate cate01 blue'><i></i>Consulting</div>\n";
		// 		contents += "<div class='logo'><img src='/images/logo_smaple01.png' alt='' /></div>\n";
		// 		contents += "<div class='info fc_fff'>\n";
		// 		contents += "<dl class='clearfix'><dt>업종</dt><dd>사회적기업</dd><dt>대표자</dt><dd>제윤경</dd><dt>기업형태</dt><dd>사회적기업</dd></dl>\n";
		// 		contents += "<div class='action fc_fff clearfix'><a href='javascript:void(0);'>관심기업 등록<i>♥</i></a><a href='javascript:void(0);'>공고 바로가기<i>→</i></a></div>\n";
		// 		contents += "</div>\n</div>\n";
		// 		contents += "</div>\n";
		// break;
		case "mod_header02":
			var contents = '<div class="module-wrap edit_wrap com_mod_header sty02">\n'
						 + '	<div class="cnt-container header clearfix">\n'
						 + '		<div id="iconArea"><div class="biz_cate cate22 green"><i></i></div></div>\n'
						 + '		<div class="logo imgCi"><img src="/images/logo_smaple01.png" alt="" /></div>\n'
						 + '		<div class="info fc_000">\n'
						 + '			<dl class="clearfix">\n'
						 + '				<dt>업종</dt>\n'
						 + '				<dd class="incCate">사회적기업</dd>\n'
						 + '				<dt>대표자</dt>\n'
						 + '				<dd class="ceo">제윤경</dd>\n'
						 + '				<dt>기업형태</dt>\n'
						 + '				<dd class="comForm">사회적기업</dd>\n'
						 + '			</dl>\n'
						 + '			<div class="action fc_000 clearfix">\n'
						 + '				<a href="javascript:void(0);" id="scrapYn" onclick="onCntNew();">관심기업 등록<i>♥</i></a>\n'
						 + '				<a href="javascript:void(0);" id="copyUrlNew" onclick="copyUrlNew();" data-clipboard-action="copy">공고 바로가기<i>→</i></a>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		// Anchor Tab
		// case "mod_anc_tab01":
		// 	var contents = "<div class='module-wrap edit_wrap bg_color com_mod_anchor sty01'>\n";
		// 		contents += "<div class='cnt-container fc_919191'>\n";
		// 		contents += "<ul>\n"
		// 		contents += "<li><a href='javascript:void(0);' class='active'>채용공고</a></li>\n";
		// 		contents += "<li><a href='javascript:void(0);'>취업전략</a></li>\n";
		// 		contents += "<li><a href='javascript:void(0);'>기업개요</a></li>\n";
		// 		contents += "<li><a href='javascript:void(0);'>현직자 리뷰</a></li>\n";
		// 		contents += "<li> <a href='javascript:void(0);'>기업 뉴스</a></li>\n";
		// 		contents += "</ul>\n";
		// 		contents += "</div>\n</div>\n";
		// break;
		case "mod_anc_tab02":
			var contents = '<div class="module-wrap edit_wrap com_mod_anchor sty02">\n'
						 + '	<div class="cnt-container fc_fff">\n'
						 + '		<ul>\n'
						 + '			<li><a href="#summary" class="active">기업개요</a></li>\n'
						 + '			<li><a href="#product">제품소개</a></li>\n'
						 + '			<li><a href="#recruit">채용공고</a></li>\n'
						 + '			<li> <a href="#news">기업뉴스</a></li>\n'
						 + '		</ul>\n'
						 + '		<div class="siteGo">사이트</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		// 공통
		case "mod_com_recruit":  //채용공고
			var contents = '<a name="recruit"></a>\n'
						 + '<div class="module-wrap edit_wrap com_mod_recruit sty01" id="recruitArea">\n'
						 + '	<div class="bg_bot"></div>\n'
						 + '	<div class="cnt-container" id="recruitContainer">\n'
						 + '		<h3>채용공고</h3>\n'
						 + '		<table class="tb_recruit otherRecruit" summary="채용공고" >\n'
						 + '			<thead>\n'
						 + '			<tr>\n'
						 + '				<th>접수기간</th>\n'
						 + '				<th>채용제목</th>\n'
						 + '				<th>고용형태</th>\n'
						 + '			</tr>\n'
						 + '			</thead>\n'
						 + '			<tbody id="otherRecruitList">\n'
						 + '				<tr>\n<td>2021.05.31 까지</td><td>풀스택 개발자 채용/경력채용/급여250만원</td><td>정규직<a href="javascript:void(0);" class="btn apply">지원하기</a></td>\n</tr>\n'
						 + '				<tr>\n<td>상시채용</td><td>생산직 지원 채용/경력 무관/급여220만원</td><td>계약직<a href="javascript:void(0);" class="btn apply">지원하기</a></td>\n</tr>\n'
						 + '			</tbody>\n'
						 + '		</table>\n'
						 + '		<div class="box_recruit_wrap swiper">\n'
						 + '			<div class="swiper-wrapper">\n'
						 + '				<div class="box_recruit swiper-slide">\n'
						 + '					<h4>\n'
						 + '						<a href="javascript:;" >채용공고명</a>\n'
						 + '						<span class="period">오늘까지</span>\n'
						 + '					</h4>\n'
						 + '					<hr/>\n'
						 + '					<div class="detail_wrap">\n'
						 + '						<div>\n'
						 + '							<h5>지원자격</h5>\n'
						 + '							<dl class="clearfix">\n'
						 + '								<dt>경력</dt>\n'
						 + '								<dd>경력무관</dd>\n'
						 + '								<dt>학력</dt>\n'
						 + '								<dd>고졸이상</dd>\n'
						 + '								<dt>우대사항</dt>\n'
						 + '								<dd>인근거주자, 1종보통운전면허</dd>\n'
						 + '							</dl>\n'
						 + '						</div>\n'
						 + '						<div>\n'
						 + '							<h5>근무조건</h5>\n'
						 + '							<dl class="clearfix">\n'
						 + '								<dt>고용형태</dt>\n'
						 + '								<dd>정규직</dd>\n'
						 + '								<dt>급여</dt>\n'
						 + '								<dd>220만원 이상</dd>\n'
						 + '								<dt>근무지역</dt>\n'
						 + '								<dd>경기도 전체</dd>\n'
						 + '							</dl>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="swiper-pagination"></div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_com_news":  // 뉴스
			var contents = '<a name="news"></a>\n'
						 + '<div class="module-wrap edit_wrap com_mod_news sty01">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div id="news_wrap">\n'
						 + '			<div class="news_row">\n'
						 + '				<a href="javascript:vodi(0);" target="_blank" class="tit">뉴스 제목</a>\n'
						 + '				<div class="desc">뉴스 내용 뉴스 내용 뉴스 내용 뉴스 내용 뉴스 내용</div>\n'
						 + '				<div class="reg_date">2021.01.01</div>\n'
						 + '			</div>\n'
						 + '			<div class="news_row">\n'
						 + '				<a href="javascript:vodi(0);" target="_blank" class="tit">뉴스 제목</a>\n'
						 + '				<div class="desc">뉴스 내용 뉴스 내용 뉴스 내용 뉴스 내용 뉴스 내용</div>\n'
						 + '				<div class="reg_date">2021.01.01</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '		<div id="paging_wrap" class="paging_wrap">\n'
						 + '			<a href="javascript:void(0);" class="prev disable">이전</a><a href="javascript:void(0);" class="current">1</a><a href="javascript:void(0);">2</a><a href="javascript:void(0);">3</a><a href="javascript:void(0);">4</a><a href="javascript:void(0);">5</a><a href="javascript:void(0);" class="next">다음</a>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_com_map":  // 지도
			var contents = '<div class="module-wrap edit_wrap com_mod_map">\n'
						 + '	<div id="map"></div>\n'
						 + '	<div class="map_info_wrap">\n'
						 + '		<div class="com_info">\n'
						 + '			<div class="comName">기업명</div>\n'
						 + '			<a href="javascript:void(0);" target="_blank" class="find_road">길 찾기</a>\n'
						 + '			<p class="comAddress">주소</p>\n'
						 + '			<p class="tel">전화번호</p>\n'
						 + '		</div>\n'
						 + '		<div class="around_wrap">\n'
						 + '			<ul id="category">\n'
						 + '				<li id="MT1" data-order="0">\n' 
						 + '					<span class="category_bg mt1"></span>\n'
						 + '					대형마트\n'
						 + '				</li>\n'       
						 + '				<li id="CS2" data-order="1">\n' 
						 + '					<span class="category_bg cs2"></span>\n'
						 + '					편의점\n'
						 + '				</li>\n'  
						 + '				<li id="AC5" data-order="2">\n' 
						 + '					<span class="category_bg ac5"></span>\n'
						 + '					학원\n'
						 + '				</li>\n'  
						 + '				<li id="PK6" data-order="3">\n' 
						 + '					<span class="category_bg pk6"></span>\n'
						 + '					주차장\n'
						 + '				</li>\n'  
						 + '				<li id="OL7" data-order="4">\n' 
						 + '					<span class="category_bg ol7"></span>\n'
						 + '					주유소\n'
						 + '				</li>\n'  
						 + '				<li id="SW8" data-order="5">\n' 
						 + '					<span class="category_bg sw8"></span>\n'
						 + '					지하철\n'
						 + '				</li>\n'
						 + '				<li id="BK9" data-order="6">\n' 
						 + '					<span class="category_bg bk9"></span>\n'
						 + '					은행\n'
						 + '				</li>\n' 
						 + '				<li id="CT1" data-order="7">\n' 
						 + '					<span class="category_bg ct1"></span>\n'
						 + '					문화시설\n'
						 + '				</li>\n'       
						 + '				<li id="AT4" data-order="8">\n' 
						 + '					<span class="category_bg at4"></span>\n'
						 + '					관광명소\n'
						 + '				</li>\n'  
						 + '				<li id="AD5" data-order="9">\n' 
						 + '					<span class="category_bg ad5"></span>\n'
						 + '					숙박\n'
						 + '				</li>\n'  
						 + '				<li id="FD6" data-order="10">\n' 
						 + '					<span class="category_bg fd6"></span>\n'
						 + '					음식점\n'
						 + '				</li>\n'  
						 + '				<li id="CE7" data-order="11">\n' 
						 + '					<span class="category_bg ce7"></span>\n'
						 + '					카페\n'
						 + '				</li>\n'  
						 + '				<li id="HP8" data-order="12">\n'
						 + '					<span class="category_bg hp8"></span>\n'
						 + '					병원\n'
						 + '				</li>\n'
						 + '				<li id="PM9" data-order="14">\n' 
						 + '					<span class="category_bg pm9"></span>\n'
						 + '					약국\n'
						 + '				</li>\n'   
						 + '			</ul>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		// SWOT
		case "mod_inf_swot01":
			var contents = ''
						+ '<div class="module-wrap edit_wrap inf_mod_swot sty01">\n'
						+ '	<div class="cnt-container swot_wrap">\n'
						+ '		<div class="title">\n'
						+ '			SWOT<br/>분석\n'
						+ '			<hr/>\n'
						+ '			<div class="imgCi"><img src="/images/logo_smaple01.png" alt="" /></div>\n'
						+ '		</div>\n'
						+ '		<div class="swotS">\n'
						+ '			<div class="tit">strengths</div>\n'
						+ '			<div class="desc">국내 스마트 홈 IoT허브 디바이스 시장점유율 1위</div>\n'
						+ '		</div>\n'
						+ '		<div class="swotW">\n'
						+ '			<div class="tit">weakenesses</div>\n'
						+ '			<div class="desc">코로나19 여파로 인한 서비스 위축</div>\n'
						+ '		</div>\n'
						+ '		<div class="swotO">\n'
						+ '			<div class="tit">opportunities</div>\n'
						+ '			<div class="desc">의료용 허브 디바이스 신규 개발을 통한 해외시장 개척</div>\n'
						+ '		</div>\n'
						+ '		<div class="swotT">\n'
						+ '			<div class="tit">threats</div>\n'
						+ '			<div class="desc">자본력 한계에 따른 안정적인 투자여력 미흡</div>\n'
						+ '		</div>\n'
						+ '	</div>\n'
						+ '</div>';
		break;
		case "mod_inf_swot02":
			var contents = ''
						+ '<div class="module-wrap edit_wrap inf_mod_swot sty02">\n'
						+ '	<div class="cnt-container">\n'
						+ '		<div class="title">\n'
						+ '			<div class="imgCi"><img src="/images/logo_smaple01.png" alt="" /></div>\n'
						+ '			SWOT분석\n'
						+ '		</div>\n'
						+ '		<div class="swot_wrap mgtop_80">\n'
						+ '			<div class="swotS">\n'
						+ '				<div class="tit">strengths</div>\n'
						+ '				<div class="desc">국내 스마트 홈 IoT허브 디바이스 시장점유율 1위</div>\n'
						+ '			</div>\n'
						+ '			<div class="swotW">\n'
						+ '				<div class="tit">weakenesses</div>\n'
						+ '				<div class="desc">코로나19 여파로 인한 서비스 위축</div>\n'
						+ '			</div>\n'
						+ '			<div class="swotO">\n'
						+ '				<div class="tit">opportunities</div>\n'
						+ '				<div class="desc">의료용 허브 디바이스 신규 개발을 통한 해외시장 개척</div>\n'
						+ '			</div>\n'
						+ '			<div class="swotT">\n'
						+ '				<div class="tit">threats</div>\n'
						+ '				<div class="desc">자본력 한계에 따른 안정적인 투자여력 미흡</div>\n'
						+ '			</div>\n'
						+ '		</div>\n'
						+ '	</div>\n'
						+ '</div>';
		break;
		case "mod_inf_swot03":
		var contents = ''
						+ '<div class="module-wrap edit_wrap inf_mod_swot sty03">\n'
						+ '	<div class="cnt-container">\n'
						+ '		<div class="swot_wrap">\n'
						+ '			<div class="swotS">\n'
						+ '				<div class="txt">\n'
						+ '					<div class="tit">Strengths</div>\n'
						+ '					<div class="desc">Strengths\n'
						+ '					</div>\n'
						+ '				</div>\n'
						+ '			</div>\n'
						+ '			<div class="swotW">\n'
						+ '				<div class="txt">\n'
						+ '					<div class="tit">weakenesses</div>\n'
						+ '					<div class="desc">weakenesses\n'
						+ '					</div>\n'
						+ '				</div>\n'
						+ '			</div>\n'
						+ '			<div class="swotO">\n'
						+ '				<div class="txt">\n'
						+ '					<div class="tit">opportunities</div>\n'
						+ '					<div class="desc">opportunities\n'
						+ '					</div>\n'
						+ '				</div>\n'
						+ '			</div>\n'
						+ '			<div class="swotT">\n'
						+ '				<div class="txt">\n'
						+ '					<div class="tit">threats</div>\n'
						+ '					<div class="desc">threats\n'
						+ '					</div>\n'
						+ '				</div>\n'
						+ '			</div>\n'
						+ '		</div>\n'
						+ '	</div>\n'
						+ '</div>';
		break;
		case "mod_inf_swot04":
		var contents = ''
			     	 + '<div class="module-wrap edit_wrap inf_mod_swot sty04">\n'
					 + '	<div class="cnt-container swot_wrap">\n'
					 + '		<div class="swotS">\n'
					 + '			<div class="tit">strengths</div>\n'
					 + '			<div class="desc">strengths</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotW">\n'
					 + '			<div class="tit">weakenesses</div>\n'
					 + '			<div class="desc">weakenesses</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotO">\n'
					 + '			<div class="tit">opportunities</div>\n'
					 + '			<div class="desc">opportunities</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotT">\n'
					 + '			<div class="tit">threats</div>\n'
					 + '			<div class="desc">threats</div>\n'
					 + '		</div>\n'
					 + '	</div>\n'
					 + '</div>';
		break;
		case "mod_inf_swot05":
		var contents = ''
				     + '<div class="module-wrap edit_wrap inf_mod_swot sty05">\n'
					 + '	<div class="cnt-container swot_wrap">\n'
					 + '		<div class="swotS">\n'
					 + '			<span>S</span>\n'
					 + '			<div class="tit">strengths</div>\n'
					 + '			<div class="desc">strengths</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotW">\n'
					 + '			<span>W</span>\n'
					 + '			<div class="tit">weakenesses</div>\n'
					 + '			<div class="desc">weakenesses</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotO">\n'
					 + '			<span>O</span>\n'
					 + '			<div class="tit">opportunities</div>\n'
					 + '			<div class="desc">opportunities</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotT">\n'
					 + '			<span>T</span>\n'
					 + '			<div class="tit">threats</div>\n'
					 + '			<div class="desc">threats</div>\n'
					 + '		</div>\n'
					 + '	</div>\n'
					 + '</div>';
		break;
		case "mod_rec_swot02":
		var contents = ''
					 + '<div class="module-wrap edit_wrap rec_mod_swot sty02">\n'
					 + '	<div class="swot_wrap">'
					 + '		<div class="diagram_area">\n'
					 + '		<div class="cnt-container">\n'
					 + '			<ul>\n'
					 + '				<li class="swotS">\n'
					 + '					<p><strong>S</strong>Strengths</p>\n'
					 + '				</li>\n'
					 + '				<li class="swotW">\n'
					 + '					<p><strong>S</strong>Weaknesses</p>\n'
					 + '				</li>\n'
					 + '				<li class="swotO">\n'
					 + '					<p><strong>S</strong>Opportunities</p>\n'
					 + '				</li>\n'
					 + '				<li class="swotT">\n'
					 + '					<p><strong>S</strong>Threats</p>\n'
					 + '				</li>\n'
					 + '			</ul>\n'
					 + '		</div>\n'
					 + '		</div>\n'
					 + '		<div class="txt">\n'
					 + '		<div class="cnt-container">\n'
					 + '		<dl class="swotS">\n'
					 + '			<dt>Strengths</dt>\n'
					 + '			<dd>Strengths</dd>\n'
					 + '		</dl>\n'
					 + '		<dl class="swotW">\n'
					 + '			<dt>Weaknesses</dt>\n'
					 + '			<dd>Weaknesses</dd>\n'
					 + '		</dl>\n'
					 + '		<dl class="swotO">\n'
					 + '			<dt>Opportunities</dt>\n'
					 + '			<dd>Opportunities</dd>\n'
					 + '		</dl>\n'
					 + '		<dl class="swotT">\n'
					 + '			<dt>Threats</dt>\n'
					 + '			<dd>Threats</dd>\n'
					 + '		</dl>\n'
					 + '		</div>\n'
					 + '		</div>\n'
					 + '		</div>\n'
					 + '	</div>\n'
					 + '</div>';
		break;
		case "mod_rec_swot03":
		var contents = ''
					 + '<div class="module-wrap edit_wrap rec_mod_swot sty03">\n'
					 + '	<div class="cnt-container swot_wrap">'
					 + '		<div class="diagram_area">\n'
					 + '			<ul>\n'
					 + '			<li class="title">기업 SWOT<br />분석</li>'
					 + '				<li class="swotS">\n'
					 + '					<p><strong>S</strong>Strengths</p>\n'
					 + '				</li>\n'
					 + '				<li class="swotW">\n'
					 + '					<p><strong>S</strong>Weaknesses</p>\n'
					 + '				</li>\n'
					 + '				<li class="swotO">\n'
					 + '					<p><strong>S</strong>Opportunities</p>\n'
					 + '				</li>\n'
					 + '				<li class="swotT">\n'
					 + '					<p><strong>S</strong>Threats</p>\n'
					 + '				</li>\n'
					 + '			</ul>\n'
					 + '		</div>\n'
					 + '		<div class="txt">\n'
					 + '		<div class="swotS">\n'
					 + '			<div class="tit">Strengths</div>\n'
					 + '			<div class="desc">Strengths</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotW">\n'
					 + '			<div class="tit">Weaknesses</div>\n'
					 + '			<div class="desc">Weaknesses</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotO">\n'
					 + '			<div class="tit">Opportunities</div>\n'
					 + '			<div class="desc">Opportunities</div>\n'
					 + '		</div>\n'
					 + '		<div class="swotT">\n'
					 + '			<div class="tit">Threats</div>\n'
					 + '			<div class="desc">Threats</div>\n'
					 + '		</div>\n'
					 + '		</div>\n'
					 + '		</div>\n'
					 + '	</div>\n'
					 + '</div>';
		break;
		case "mod_rec_swot04":
		var contents = ''
					 + '<div class="module-wrap edit_wrap rec_mod_swot sty04">\n'
					 + '	<div class="cnt-container">'
					 + '		<div class="swot_wrap">\n'	
					 + '			<div class="swotS">\n'	
					 + '				<div class="diagram_area">\n'	
					 + '					<p><strong>S</strong>Strengths</p>\n'	
					 + '				</div>\n'	
					 + '				<div class="txt">\n'	
					 + '					<div class="tit">Strengths</div>\n'	
					 + '					<div class="desc">Strengths</div>\n'	
					 + '				</div>\n'	
					 + '			</div>'
					 + '			<div class="swotW">\n'	
					 + '				<div class="diagram_area">\n'	
					 + '					<p><strong>W</strong>Weaknesses</p>\n'	
					 + '				</div>\n'	
					 + '				<div class="txt">\n'	
					 + '					<div class="tit">Weaknesses</div>\n'	
					 + '					<div class="desc">Weaknesses</div>\n'	
					 + '				</div>\n'	
					 + '			</div>'
					 + '			<div class="swotO">\n'	
					 + '				<div class="diagram_area">\n'	
					 + '					<p><strong>O</strong>Opportunities</p>\n'	
					 + '				</div>\n'	
					 + '				<div class="txt">\n'	
					 + '					<div class="tit">Opportunities</div>\n'	
					 + '					<div class="desc">Opportunities</div>\n'	
					 + '				</div>\n'	
					 + '			</div>'
					 + '			<div class="swotT">\n'	
					 + '				<div class="diagram_area">\n'	
					 + '					<p><strong>T</strong>Threats</p>\n'	
					 + '				</div>\n'	
					 + '				<div class="txt">\n'	
					 + '					<div class="tit">Threats</div>\n'	
					 + '					<div class="desc">Threats</div>\n'	
					 + '				</div>\n'	
					 + '			</div>'
					 + '	</div>\n'
					 + '	</div>\n'
					 + '</div>';
		break;	
		case "mod_rec_swot05":
		var contents = ''
					 + '<div class="module-wrap edit_wrap rec_mod_swot sty05">\n'
					 + '	<div class="cnt-container">\n'
					 + '		<div class="swot_wrap">\n'
					 + '		<div>\n'
					 + '			<div class="swotS">\n'
					 + '				<div class="txt">\n'
					 + '					<div class="tit">Strengths</div>\n'
					 + '					<div class="desc">Strengths\n'
					 + '					</div>\n'
					 + '				</div>\n'
					 + '			</div>\n'
					 + '			<div class="swotW">\n'
					 + '				<div class="txt">\n'
					 + '					<div class="tit">weakenesses</div>\n'
					 + '					<div class="desc">weakenesses\n'
					 + '					</div>\n'
					 + '				</div>\n'
					 + '			</div>\n'
					 + '			<div class="swotO">\n'
					 + '				<div class="txt">\n'
					 + '					<div class="tit">opportunities</div>\n'
					 + '					<div class="desc">opportunities\n'
					 + '					</div>\n'
					 + '				</div>\n'
					 + '			</div>\n'
					 + '			<div class="swotT">\n'
					 + '				<div class="txt">\n'
					 + '					<div class="tit">threats</div>\n'
					 + '					<div class="desc">threats\n'
					 + '					</div>\n'
					 + '				</div>\n'
					 + '			</div>\n'
					 + '		</div>\n'
					 + '		</div>\n'
					 + '	</div>\n'
					 + '</div>';
		break;
		// 기업 리뷰	
		case "mod_mag_review01":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_review sty01">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="review_wrap">\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_mag_review02":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_review sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="review_wrap">\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_mag_review03":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_review sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="review_wrap">\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_mag_review05":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_review sty05">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="review_wrap">\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_sns_review01":
			var contents = ''
						 + '<div class="module-wrap edit_wrap sns_mod_review sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="review_wrap">\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '			<div class="item">\n'
						 + '				<p class="desc">기업리뷰</p>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mod_rec_review01":
				var contents = ''
							 + '<div class="module-wrap edit_wrap rec_mod_review sty01">\n'
							 + '	<div class="cnt-container">\n'
							 + '		<div class="review_wrap">\n'
							 + '			<div class="item">\n'
							 + '				<p class="desc">기업리뷰</p>\n'
							 + '			</div>\n'
							 + '			<div class="item">\n'
							 + '				<p class="desc">기업리뷰</p>\n'
							 + '			</div>\n'
							 + '			<div class="item">\n'
							 + '				<p class="desc">기업리뷰</p>\n'
							 + '			</div>\n'
							 + '			<div class="item">\n'
							 + '				<p class="desc">기업리뷰</p>\n'
							 + '			</div>\n'
							 + '			<div class="item">\n'
							 + '				<p class="desc">기업리뷰</p>\n'
							 + '			</div>\n'
							 + '			<div class="item">\n'
							 + '				<p class="desc">기업리뷰</p>\n'
							 + '			</div>\n'
							 + '		</div>\n'
							 + '	</div>\n'
							 + '</div>\n';
		break;
		// 백분위정보
		case "mod_inf_percent01":
			var contents = ''
						 + '<div class="module-wrap edit_wrap inf_mod_percent sty01">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<ul class="type_pink">\n'
						 + '			<li></li>\n'
						 + '			<li>\n'
						 + '				성장성<span class="bpGrowthability">상위25%</span>\n'
						 + '			</li>\n'
						 + '			<li></li>\n'
						 + '		</ul>\n'
						 + '		<ul class="type_orange">\n'
						 + '			<li></li>\n'
						 + '			<li>\n'
						 + '				규모형태<span class="bpScale">상위33%</span>\n'
						 + '			</li>\n'
						 + '			<li></li>\n'
						 + '		</ul>\n'
						 + '		<ul class="type_green">\n'
						 + '			<li></li>\n'
						 + '			<li></li>\n'
						 + '			<li>\n'
						 + '				안정성<span class="bpStability">상위20%</span>\n'
						 + '			</li>\n'
						 + '		</ul>\n'
						 + '		<ul class="type_blue">\n'
						 + '			<li></li>\n'
						 + '			<li>\n'
						 + '				수익성<span class="bpProfitability">상위57%</span>\n'
						 + '			</li>\n'
						 + '			<li></li>\n'
						 + '		</ul>\n'
						 + '	</div>\n'
						 + '</div>';
		break;
		case "mod_inf_percent02":
			var contents = ''
						 + '<div class="module-wrap edit_wrap inf_mod_percent sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="growth">성장성<span class="bpGrowthability">상위25%</span></div>\n'
						 + '			<div class="scale">규모형태<span class="bpScale">상위33%</span></div>\n'
						 + '			<div class="stable">안정성<span class="bpStability">상위20%</span></div>\n'
						 + '			<div class="profit">수익성<span class="bpProfitability">상위57%</span></div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>';
		break;
		case "mag_mod_percent05":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_percent sty05">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mag_mod_percent04":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_percent sty04">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mag_mod_percent06":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_percent sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="swiper percent">\n'
						 + '			<div class="swiper-wrapper">\n'
						 + '				<div class="swiper-slide">\n'
						 + '					<div><img src="images/@img_percent_3308100104_01.png" alt=""/></div>\n'
						 + '					<div>\n'
						 + '						<span class="cate">규모형태</span><span class="value bpScale">-</span><br/>\n'
						 + '						<span class="desc">정확하고 신뢰할 수 있는 센싱 테크놀로지</span>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-slide">\n'
						 + '					<div><img src="images/@img_percent_3308100104_02.png" alt=""/></div>\n'
						 + '					<div>\n'
						 + '						<span class="cate">수익성</span><span class="value bpProfitability">-</span><br/>\n'
						 + '						<span class="desc">모든 어플리케이션에 원활하게 통합되는 제품 디자인</span>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-slide">\n'
						 + '					<div><img src="images/@img_percent_3308100104_03.png" alt=""/></div>\n'
						 + '					<div>\n'
						 + '						<span class="cate">안정성</span><span class="value bpStability">-</span><br/>\n'
						 + '						<span class="desc">설치가 간편하여, 귀중한 시간과 자원을 절약할 수 있는 통합 솔루션</span>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-slide">\n'
						 + '					<div><img src="images/@img_percent_3308100104_04.png" alt=""/></div>\n'
						 + '					<div>\n'
						 + '						<span class="cate">성장성</span><span class="value bpGrowthability">-</span><br/>\n'
						 + '						<span class="desc">기술, 영업 및 고객 서비스 팀의 고품질 서비스</span>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '		<div class="swiper-pagination"></div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var percentSlider = new Swiper(".percent",{\n'
						 + '		slidesPerView: 1,\n'
						 + '		slidesPerGroup: 1,\n'
						 + '		spaceBetween: 20,\n'
						 + '		loop: true,\n'
						 + '		pagination: {\n'
						 + '			el: ".mag_mod_percent .swiper-pagination",\n'
						 + '			clickable: true,\n'
						 + '		},\n'
						 + '		breakpoints:{\n'
						 + '			780: {\n'
						 + '				slidesPerView: 2,\n'
						 + '				slidesPerGroup: 2,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_bro_percent01":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_percent sty01">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="title">\n'
						 + '			<img src="/images/bro_percent01_ico01.png" alt="이미지">\n'
						 + '		</div>\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "mag_mod_percent03":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_percent sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "inf_mod_percent03":
			var contents = ''
						 + '<div class="module-wrap edit_wrap inf_mod_percent sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "inf_mod_percent04":
			var contents = ''
						 + '<div class="module-wrap edit_wrap inf_mod_percent sty04">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '		<div class="title">\n'
						 + '			title\n'
						 + '		</div>\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "inf_mod_percent05":
			var contents = ''
						 + '<div class="module-wrap edit_wrap inf_mod_percent sty05">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="growth">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>성장성<span class="bpGrowthability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="scale">\n'
						 + '				<span class="ico"></span>\n'
						 + '					<div>규모형태<span class="bpScale">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>안정성<span class="bpStability">-</span></div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<span class="ico"></span>\n'
						 + '				<div>수익성<span class="bpProfitability">-</span></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "rec_mod_percent02":
			var contents = ''
						 + '<div class="module-wrap edit_wrap rec_mod_percent sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="scale">\n'
						 + '				<p>규모형태</p>\n'
						 + '				<div class="circle">\n'
						 + '					<p>상위 <strong class="bpScale">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<p>수익성</p>\n'
						 + '				<div class="circle">\n'
						 + '					<p>상위 <strong class="bpProfitability">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<p>안정성</p>\n'
						 + '				<div class="circle">\n'
						 + '				<p>상위 <strong class="bpStability">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<p>성장성</p>\n'
						 + '				<div class="circle">\n'
						 + '					<p>상위 <strong class="bpGrowthability">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		case "rec_mod_percent03":
			var contents = ''
						 + '<div class="module-wrap edit_wrap rec_mod_percent sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="percent_wrap">\n'
						 + '			<div class="scale">\n'
						 + '				<p>규모형태</p>\n'
						 + '				<div class="circle">\n'
						 + '					<p>상위 <strong class="bpScale">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="profit">\n'
						 + '				<p>수익성</p>\n'
						 + '				<div class="circle">\n'
						 + '					<p>상위 <strong class="bpProfitability">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="stable">\n'
						 + '				<p>안정성</p>\n'
						 + '				<div class="circle">\n'
						 + '				<p>상위 <strong class="bpStability">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="growth">\n'
						 + '				<p>성장성</p>\n'
						 + '				<div class="circle">\n'
						 + '					<p>상위 <strong class="bpGrowthability">-</strong>%</p>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n';
		break;
		// 사업분야
		case "mag_mod_biz01":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_biz sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<h3>사업분야</h3>\n'
						 + '		<div class="msgAdd">㈜빅텍은 전자전,군용전원,감시/정찰 분야 등 방위산업을 통해 국가안보에 기여하고 있으며, 친환경 모빌리티인 공공자전거 시스템을 통해 더 편리하고 지속가능한 생활환경을 만들고 있습니다. </div>\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv swiper">\n'
						 + '				<div class="swiper-wrapper">'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '								<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '								<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '								<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '								<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-pagination"></div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						//  + '$(".droparea").append(contents).promise().done(function(){\n'
						//  + '	var magBiz03 = $(".mag_mod_biz.sty03 .bizDiv");\n'
						//  + '	magBiz03.addClass("swiper");\n'
						//  + '	magBiz03.wrapInner("<div class=\"swiper-wrapper\"></div>");\n'
						//  + '	var item = magBiz03.children().children().wrap("<div class=\"swiper-slide\"></div>");\n'
						//  + '	magBiz03.append("<div class=\"swiper-pagination\"></div>");\n'
						//  + '	magBiz03.append("<div class=\"swiper-button-prev\"></div>");\n'
						//  + '	magBiz03.append("<div class=\"swiper-button-next\"></div>");\n'
						 + '	var bizSlider = new Swiper(".mag_mod_biz.sty03 .bizDiv", {\n'
						 + '		slidesPerView: 3,\n'
						 + '		spaceBetween: 30,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".mag_mod_biz.sty03 .swiper-button-next",\n'
						 + '			prevEl: ".mag_mod_biz.sty03 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 3,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						//  + '});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz02":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_biz sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv swiper">\n'
						 + '				<div class="swiper-wrapper">'
						 + '					<div class="swiper-slide">\n'
						 + '						<div><img src="/images/biz_sampleImg.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div><img src="/images/biz_sampleImg.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div><img src="/images/biz_sampleImg.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div><img src="/images/biz_sampleImg.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-pagination"></div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var bizSlider = new Swiper(".mag_mod_biz.sty02 .bizDiv", {\n'
						 + '		slidesPerView: 3,\n'
						 + '		spaceBetween: 30,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".mag_mod_biz.sty02 .swiper-button-next",\n'
						 + '			prevEl: ".mag_mod_biz.sty02 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 3,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz03":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_biz sty04">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="txt">\n'
						 + '				<p class="msgAdd">끊임없이 성장하는<br>더 나은 세상을 만들어 갑니다.</p>\n'
						 + '				<h3>사업<span>영역</span></h3>\n'
						 + '				<div class="swiper-pagination"></div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '			<div class="bizDiv swiper">\n'
						 + '				<div class="swiper-wrapper">'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg02.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var bizSlider = new Swiper(".mag_mod_biz.sty04 .bizDiv", {\n'
						 + '		slidesPerView: 2,\n'
						 + '		spaceBetween: 30,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".mag_mod_biz.sty04 .swiper-button-next",\n'
						 + '			prevEl: ".mag_mod_biz.sty04 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 2,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz04":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_biz sty05">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<h3>사업영역</h3>\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv swiper">\n'
						 + '				<div class="swiper-wrapper">'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg03.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg03.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg03.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-pagination"></div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var bizSlider = new Swiper(".mag_mod_biz.sty05 .bizDiv", {\n'
						 + '		slidesPerView: 1,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".mag_mod_biz.sty05 .swiper-button-next",\n'
						 + '			prevEl: ".mag_mod_biz.sty05 .swiper-button-prev"\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz05":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_biz sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="mission_wrap">\n'
						 + '			<p>MISSION</p>\n'
						 + '			<div class="mission">수요자 맞춤형 고용서비스 제공으로 고용기회 확대와 도민의 복지증진</div>\n'
						 + '		</div>\n'
						 + '		<h3>주요 사업 안내</h3>\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv swiper">\n'
						 + '				<div class="swiper-wrapper">'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '							<h4>타이틀</h4>\n'
						 + '							<p>소개</p>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-pagination"></div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var bizSlider = new Swiper(".bro_mod_biz.sty02 .bizDiv", {\n'
						 + '		slidesPerView: 4,\n'
						 + '		spaceBetween: 30,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".bro_mod_biz.sty02 .swiper-button-next",\n'
						 + '			prevEl: ".bro_mod_biz.sty02 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 3\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 4,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz06":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_biz sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="tab_wrap">\n'
						 + '			<ul class="tabs">\n'
						 + '				<li><a href="javascript:vold" data-tab="타이틀1" class="on">타이틀1</a></li>\n'
						 + '				<li><a href="javascript:vold" data-tab="타이틀2" class="">타이틀2</a></li>\n'
						 + '				<li><a href="javascript:vold" data-tab="타이틀3" class="">타이틀3</a></li>\n'
						 + '				<li><a href="javascript:vold" data-tab="타이틀4" class="">타이틀4</a></li>\n'
						 + '				<li><a href="javascript:vold" data-tab="타이틀5" class="">타이틀5</a></li>\n'
						 + '			</ul>\n'
						 + '		</div>\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv">\n'
						 + '				<div class="타이틀1" style="display: flex;">\n'
						 + '					<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4>타이틀1</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="타이틀2" style="display: none;">\n'
						 + '					<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4>타이틀2</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="타이틀3" style="display: none;">\n'
						 + '					<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4>타이틀3</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="타이틀4" style="display: none;">\n'
						 + '					<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4>타이틀4</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="타이틀5" style="display: none;">\n'
						 + '					<img src="/images/biz_sampleImg04.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4>타이틀5</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	$(".bro_mod_biz.sty03 .tabs li:first a").addClass("on");\n'
						 + '	$(".bro_mod_biz.sty03 .bizDiv > div").hide();\n'
						 + ' 	$(".bro_mod_biz.sty03 .bizDiv > div:first").show();\n'
						 + ' 	$(".bro_mod_biz.sty03 .tabs a").click(function() {\n'
						 + ' 	 	var item = $(this).attr("data-tab");\n'
						 + ' 	 	$(this).parent().siblings().children().removeClass("on");\n'
						 + ' 	 	$(this).addClass("on");\n'
						 + ' 	 	$(".bro_mod_biz.sty03 .bizDiv > div").hide();\n'
						 + ' 	 	$(".bro_mod_biz.sty03 .bizDiv > ." + item).show();\n'
						 + ' 	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz07":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_biz sty04">\n'
						+ '	<div class="cnt-container">\n'
						+ '		<div class="txt">\n'
						+ '			<p>주요사업안내</p>\n'
						+ '			<div class="img"></div>\n'
						+ '		</div>\n'
						+ '		<div class="biz_wrap">\n'
						+ '			<div class="tab_wrap">\n'
						+ '				<ul class="tabs">\n'
						+ '					<li><a href="javascript:vold" data-tab="타이틀1" class="on">타이틀1</a></li>\n'
						+ '					<li><a href="javascript:vold" data-tab="타이틀2" class="">타이틀2</a></li>\n'
						+ '					<li><a href="javascript:vold" data-tab="타이틀3" class="">타이틀3</a></li>\n'
						+ '					<li><a href="javascript:vold" data-tab="타이틀4" class="">타이틀4</a></li>\n'
						+ '					<li><a href="javascript:vold" data-tab="타이틀5" class="">타이틀5</a></li>\n'
						+ '				</ul>\n'
						+ '			</div>\n'
						+ '			<div class="bizDiv">\n'
						+ '				<div class="타이틀1" style="display: block;">\n'
						+ '					<img src="/images/biz_sampleImg05.png" alt="">\n'
						+ '					<h4>타이틀1</h4>\n'
						+ '					<p>소개</p>\n'
						+ '				</div>\n'
						+ '				<div class="타이틀2" style="display: none;">\n'
						+ '					<img src="/images/biz_sampleImg05.png" alt="">\n'
						+ '					<h4>타이틀2</h4>\n'
						+ '					<p>소개</p>\n'
						+ '				</div>\n'
						+ '				<div class="타이틀3" style="display: none;">\n'
						+ '					<img src="/images/biz_sampleImg05.png" alt="">\n'
						+ '					<h4>타이틀3</h4>\n'
						+ '					<p>소개</p>\n'
						+ '				</div>\n'
						+ '				<div class="타이틀4" style="display: none;">\n'
						+ '					<img src="/images/biz_sampleImg05.png" alt="">\n'
						+ '					<h4>타이틀4</h4>\n'
						+ '					<p>소개</p>\n'
						+ '				</div>\n'
						+ '				<div class="타이틀5" style="display: none;">\n'
						+ '					<img src="/images/biz_sampleImg05.png" alt="">\n'
						+ '					<h4>타이틀5</h4>\n'
						+ '					<p>소개</p>\n'
						+ '				</div>\n'
						+ '			</div>\n'
						+ '		</div>\n'
						+ '	</div>\n'
						+ '</div>\n'
						 + '<script>\n'
						 + '	$(".bro_mod_biz.sty04 .tabs li:first a").addClass("on");\n'
						 + '	$(".bro_mod_biz.sty04 .bizDiv > div").hide();\n'
						 + ' 	$(".bro_mod_biz.sty04 .bizDiv > div:first").show();\n'
						 + ' 	$(".bro_mod_biz.sty04 .tabs a").click(function() {\n'
						 + ' 	 	var item = $(this).attr("data-tab");\n'
						 + ' 	 	$(this).parent().siblings().children().removeClass("on");\n'
						 + ' 	 	$(this).addClass("on");\n'
						 + ' 	 	$(".bro_mod_biz.sty04 .bizDiv > div").hide();\n'
						 + ' 	 	$(".bro_mod_biz.sty04 .bizDiv > ." + item).show();\n'
						 + ' 	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz08":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_biz sty05">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="bg">\n'
						 + '			<div class="mission_wrap">\n'
						 + '				<p>MISSION</p>\n'
						 + '				<div class="mission">\n'
						 + '					<span>젊은 패기</span> 및 <span>창의적인 아이디어</span>를 바탕으로 모두가 편리하고 안전한 삶을 누릴수 있는 세상을 만드는데 이바지하고, <span>함께 적극적이고 진취적인 자세</span>로 노력합니다.\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '			<div class="biz_wrap">\n'
						 + '				<div class="bizDiv swiper">\n'
						 + '					<div class="swiper-wrapper">\n'
						 + '						<div class="swiper-slide">\n'
						 + '							<div>\n'
						 + '								<img src="/images/biz_sampleImg06.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '						<div class="swiper-slide">\n'
						 + '							<div>\n'
						 + '								<img src="/images/biz_sampleImg06.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '						<div class="swiper-slide">\n'
						 + '							<div>\n'
						 + '								<img src="/images/biz_sampleImg06.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '						<div class="swiper-slide">\n'
						 + '							<div>\n'
						 + '								<img src="/images/biz_sampleImg06.png" alt="">\n'
						 + '								<h4>타이틀</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-pagination"></div>\n'
						 + '					<div class="swiper-button-prev"></div>\n'
						 + '					<div class="swiper-button-next"></div>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var bizSlider = new Swiper(".bro_mod_biz.sty05 .bizDiv", {\n'
						 + '		slidesPerView: 4,\n'
						 + '		spaceBetween: 5,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".bro_mod_biz.sty05 .swiper-button-next",\n'
						 + '			prevEl: ".bro_mod_biz.sty05 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 3\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 4,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz09":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_biz sty06">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<h3>주요사업안내</h3>\n'
						 + '		<div class="msgAdd">직원과 회사가 함께 성장하는 회사</div>\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv">\n'
						 + '				<div class="active">\n'
						 + '					<img src="/images/biz_sampleImg07.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4 tabindex="0">타이틀1</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="">\n'
						 + '					<img src="/images/biz_sampleImg08.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4 tabindex="0">타이틀2</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="">\n'
						 + '					<img src="/images/biz_sampleImg07.png" alt="">\n'
						 + '					<div class="text_area">\n'
						 + '						<h4 tabindex="0">타이틀3</h4>\n'
						 + '						<p>소개</p>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	$(".bro_mod_biz.sty06 .bizDiv > div h4").click(function() {\n'
						 + '		$(this).parent().parent().addClass("active");\n'
						 + '		$(this).parent().parent().siblings().removeClass("active");\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mag_mod_biz10":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_biz sty07">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<h3>주요사업안내</h3>\n'
						 + '		<div class="biz_wrap">\n'
						 + '			<div class="bizDiv swiper">\n'
						 + '				<div class="swiper-wrapper">\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg09.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀1</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg09.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀2</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg09.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀3</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg09.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀4</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg09.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀5</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<div>\n'
						 + '							<img src="/images/biz_sampleImg09.png" alt="">\n'
						 + '							<div class="text_area">\n'
						 + '								<h4>타이틀6</h4>\n'
						 + '								<p>소개</p>\n'
						 + '							</div>\n'
						 + '						</div>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-pagination"></div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var bizSlider = new Swiper(".bro_mod_biz.sty07 .bizDiv", {\n'
						 + '		slidesPerView: 4,\n'
						 + '		spaceBetween: 20,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".bro_mod_biz.sty07 .swiper-button-next",\n'
						 + '			prevEl: ".bro_mod_biz.sty07 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 3\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 4,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		// 연혁
		case "mod_history01":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_history sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="history_wrap">\n'
						 + '			<div class="holder"></div>\n'
						 + '			<div id="history" class="history">\n'
						 + '				<div>\n'
						 + '					<span>2021</span>\n'
						 + '					<ul>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '					</ul>\n'
						 + '				</div>\n'
						 + '				<div>\n'
						 + '					<span>2018</span>\n'
						 + '					<ul>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '					</ul>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
		break;
		case "mod_history02":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_history sty03">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="tab_wrap">\n'
						 + '			<div class="tabs">\n'
						 + '				<a href="javascript:vold" data-tab="2021" class="on">2021</a>\n'
						 + '				<a href="javascript:vold" data-tab="2018" class="">2018</a>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '		<div class="history_wrap">\n'
						 + '			<div class="cont">\n'
						 + '				<p class="tit">국가 경쟁력을 갖추다</p>\n'
						 + '				<img src="./images/history_img01.png" alt="">\n'
						 + '				<p class="desc">제품 소프트웨어 검증 및 개발지원을 주 사업으로 전장 제품 소프트웨어의 안정성과 신뢰성 확보와 우수한 경쟁력 확보, 국제 경쟁력을 갖추다</p>\n'
						 + '			</div>\n'
						 + '			<div id="history" class="history">\n'
						 + '				<div class="2021" style="display: block;">\n'
						 + '					<span>2021</span>\n'
						 + '					<ul>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '					</ul>\n'
						 + '				</div>\n'
						 + '				<div class="2018" style="display: none;">\n'
						 + '					<span>2018</span>\n'
						 + '					<ul>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '					</ul>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	$(".bro_mod_history.sty03 .tabs a:first").addClass("on");\n'
						 + '	$(".bro_mod_history.sty03 .history > div").hide();\n'
						 + '	$(".bro_mod_history.sty03 .history > div:first").show();\n'
						 + '	$(".bro_mod_history.sty03 .tabs a").click(function() {\n'
						 + '		var item = $(this).attr("data-tab");\n'
						 + '		$(this).siblings().removeClass("on");\n'
						 + '		$(this).addClass("on");\n'
						 + '		$(".bro_mod_history.sty03 .history > div").hide();\n'
						 + '		$(".bro_mod_history.sty03 .history > ." + item).show();\n'
						 + '	});\n'
						 + '</script>\n';
		break;
		case "mod_history03":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_history sty04">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<div class="history_wrap">\n'
						 + '			<div class="cont">\n'
						 + '				<p class="tit">올　바　른<br>생　각　과<br>가　치　관</p>\n'
						 + '			</div>\n'
						 + '			<div id="history" class="history">\n'
						 + '				<div>\n'
						 + '					<span>2021</span>\n'
						 + '					<ul>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '					</ul>\n'
						 + '				</div>\n'
						 + '				<div>\n'
						 + '					<span>2018</span>\n'
						 + '					<ul>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '						<li>\n'
						 + '							<div class="month">11</div>\n'
						 + '							<div class="event"><span>연혁</span></div>\n'
						 + '						</li>\n'
						 + '					</ul>\n'
						 + '				</div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
		break;
		case "mod_history04":
			var contents = ''
						 + '<div class="module-wrap edit_wrap mag_mod_history sty02">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<h3>연혁</h3>\n'
						 + '		<div class="sero_division"></div>\n'
						 + '		<div class="addMsg">세계가 인정하는 기술력과 국내외의 여러 이해 관계자들과 함께 동행해온 경험으로, 세계 정상을 향해 계속해서 길을 만들어 나가겠습니다.</div>\n'
						 + '		<div class="history">\n'
						 + '			<div>\n'
						 + '				<span>2021</span>\n'
						 + '				<ul>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '				</ul>\n'
						 + '			</div>\n'
						 + '			<div>\n'
						 + '				<span>2018</span>\n'
						 + '				<ul>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '					<li>\n'
						 + '						<div class="month">11</div>\n'
						 + '						<div class="event"><span>연혁</span></div>\n'
						 + '					</li>\n'
						 + '				</ul>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
		break;
		case "mod_history05":
			var contents = ''
						 + '<div class="module-wrap edit_wrap bro_mod_history sty05">\n'
						 + '	<div class="cnt-container">\n'
						 + '		<h3>연혁</h3>\n'
						 + '		<div class="history_wrap">\n'
						 + '			<div id="history" class="history swiper">\n'
						 + '				<div class="swiper-wrapper">\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<span>2021</span>\n'
						 + '						<ul>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '						</ul>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<span>2018</span>\n'
						 + '						<ul>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '						</ul>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<span>2018</span>\n'
						 + '						<ul>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '						</ul>\n'
						 + '					</div>\n'
						 + '					<div class="swiper-slide">\n'
						 + '						<span>2018</span>\n'
						 + '						<ul>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '							<li>\n'
						 + '								<div class="month">11</div>\n'
						 + '								<div class="event"><span>연혁</span></div>\n'
						 + '							</li>\n'
						 + '						</ul>\n'
						 + '					</div>\n'
						 + '				</div>\n'
						 + '				<div class="swiper-button-prev"></div>\n'
						 + '				<div class="swiper-button-next"></div>\n'
						 + '			</div>\n'
						 + '		</div>\n'
						 + '	</div>\n'
						 + '</div>\n'
						 + '<script>\n'
						 + '	var historySlider = new Swiper(".bro_mod_history.sty05 .history", {\n'
						 + '		slidesPerView: 3,\n'
						 + '		spaceBetween: 30,\n'
						 + '		navigation: {\n'
						 + '			nextEl: ".bro_mod_history.sty05 .swiper-button-next",\n'
						 + '			prevEl: ".bro_mod_history.sty05 .swiper-button-prev"\n'
						 + '		},\n'
						 + '		breakpoints: {\n'
						 + '			280: {\n'
						 + '				slidesPerView: 1\n'
						 + '			},\n'
						 + '			640: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1024: {\n'
						 + '				slidesPerView: 2\n'
						 + '			},\n'
						 + '			1261: {\n'
						 + '				slidesPerView: 3,\n'
						 + '			}\n'
						 + '		}\n'
						 + '	});\n'
						 + '</script>\n';
		break;

		
		// 재무정보
		case "mod_inf_finance01":
			var contents = ''
						+ '<div class="module-wrap edit_wrap inf_mod_finance sty01">\n'
						+ '	<div class="cnt-container">\n'
						+ '		<h3>Finance Information</h3>\n'
						+ '		<ul>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiPosition">순위없음</span></div>\n'
						+ '				동종업종내 위치\n'
						+ '			</li>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiCapital">100</span></div>\n'
						+ '				자본금(백만원)\n'
						+ '			</li>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiProfit">-48</span></div>\n'
						+ '				당기순이익(백만원)\n'
						+ '			</li>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiSales">555</span></div>\n'
						+ '				매출액(백만원)\n'
						+ '			</li>\n'
						+ '		</ul>\n'
						+ '	</div>\n'
						+ '</div>';
		break;
		case "mod_inf_finance02":
			var contents = ''
						+ '<div class="module-wrap edit_wrap inf_mod_finance sty02">\n'
						+ '	<div class="cnt-container txt_center">\n'
						+ '		<h3>Finance Information</h3>\n'
						+ '		<ul class="clearfix">\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiPosition">9위</span></div>\n'
						+ '				동종업종내 위치\n'
						+ '			</li>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiCapital">5,731</span></div>\n'
						+ '				자본금(백만원)\n'
						+ '			</li>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiProfit">2,948</span></div>\n'
						+ '				당기순이익(백만원)\n'
						+ '			</li>\n'
						+ '			<li>\n'
						+ '				<div class="ico"></div>\n'
						+ '				<div class="cnt"><span class="fiSales">3,162</span></div>\n'
						+ '				매출액(백만원)\n'
						+ '			</li>\n'
						+ '		</ul>\n'
						+ '	</div>\n'
						+ '</div>';
		break;

		

		
			
					
			
	}
	return contents;
}